### ISSUE TITLE
not working with Meteor 1.3.1

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#63]
Hi @JoeyAndres,
I update [demo application](https://github.com/meteoric124/meteoric-demo) master branch to 1.3.1 and then project not working at all and return this error on client and show iron-router error page:

```
Error: Cannot find module 'jquery'
TypeError: Package['jandres:ionic'] is undefined
ReferenceError: meteorInstall is not defined
```

You can see this here too:

![meteoric](https://cloud.githubusercontent.com/assets/8266479/14457753/17a727ba-00c2-11e6-81d5-722da5c258d6.png)

**Comment by cyclops24** [comment]
@JoeyAndres do you have any idea that why Meteoric 1.0.0 not working with Meteor 1.3 but Meteoric 1.2.4 alpha (or beta) works well with Meteor 1.3?

**Comment by JoeyAndres** [comment]
I'll close this. This was caused when my versioning was messed up (1.24 instead of 1.2.4) as we discussed in private in gitter.
